name: Deploy Honeypot Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Base Infrastructure via Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: 'a6a131b5-d443-4556-8209-0626cb590668'
          region: eastus
          template: ./infra/main.bicep
